### ISSUE TITLE
Unable to register for updates on the website

### ISSUE THREAD

**Issue by stampf** [pax-eth/the-directory#1]
Title says it all. Message is: "Oops. Something went wrong. Please try again later."

**Comment by pax-eth** [comment]
Thanks- will take a look now.

**Comment by pax-eth** [comment]
Just tested- plugin was out of date. Just updated so it should be working. Thanks.

**Comment by stampf** [comment]
I guess it worked because it swallowed my email and brought me back to the homepage. Thanks :)
